/**
 * esbuild 기반 브라우저 번들 생성
 */

const esbuild = require('esbuild');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');

const entryPoints = [
  'src/00-polyfill.js',
  'src/01-style.js',
  'src/02-react-bundle.js',
  'src/app/main/00-react18-compat.js',
  'src/app/main/00-constants.js',
  'src/app/main/01-helpers.js',
  'src/app/main/02-dom-init.js',
  'src/app/main/03-data-cache.js',
  'src/app/main/03-data-v2.js',
  'src/app/main/03-data-api.js',
  'src/app/main/03-data-state.js',
  'src/app/main/03-data-manager.js',
  'src/app/main/04-api.js',
  'src/app/main/05-demo-mode.js',
  'src/app/main/06-merge-manager.js',
  'src/app/main/07-ui-state.js',
  'src/app/main/08-renderers-overview.js',
  'src/app/main/08-renderers-daily.js',
  'src/app/main/08-renderers-queries.js',
  'src/app/main/08-renderers-pages.js',
  'src/app/main/08-renderers-pattern.js',
  'src/app/main/08-renderers-crawl.js',
  'src/app/main/08-renderers-backlink.js',
  'src/app/main/08-renderers-diagnosis.js',
  'src/app/main/08-renderers-insight.js',
  'src/app/main/08-renderers.js',
  'src/app/main/09-ui-controls.js',
  'src/app/main/10-all-sites-view.js',
  'src/app/main/12-snapshot.js',
  'src/app/main/11-site-view.js',
  'src/app/main/13-refresh.js',
  'src/app/main/14-init.js'
];

(async () => {
  try {
    const result = await esbuild.build({
      entryPoints: ['src/app/main/14-init.js'], // 메인 진입점
      bundle: true,
      outfile: path.join(DIST_DIR, 'runtime-bundle.js'),
      platform: 'browser',
      target: 'es2015',
      format: 'iife',
      sourcemap: false,
      minify: false,
      treeShaking: true,
      external: ['react', 'ReactDOM'], // React는 별도로 처리
      banner: {
        js: '// SearchAdvisor Runtime Bundle - Generated by esbuild'
      },
      loader: {
        '.js': 'js'
      },
      resolveExtensions: ['.js'],
      mainFields: ['module', 'main'],
      // Node.js 내장 모듈 처리
      inject: [
        path.join(SRC_DIR, 'shims', 'process.js'),
        path.join(SRC_DIR, 'shims', 'buffer.js')
      ].filter(f => require('fs').existsSync(f))
    });

    console.log('✅ esbuild build complete!');
    console.log(`   Output: ${path.join(DIST_DIR, 'runtime-bundle.js')}`);

    const stats = require('fs').statSync(path.join(DIST_DIR, 'runtime-bundle.js'));
    console.log(`   Size: ${(stats.size / 1024).toFixed(2)} KB`);

  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
})();
